# Generated by Django 4.1.7 on 2023-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("content", models.TextField(max_length=500, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TweetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="tweets/")),
            ],
        ),
        migrations.CreateModel(
            name="TweetReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=200, null=True)),
                ("like", models.IntegerField(default=0)),
                ("retweet", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TweetViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impression", models.IntegerField(default=0)),
                ("engagements", models.IntegerField(default=0)),
                ("detail_expands", models.IntegerField(default=0)),
                ("new_follower", models.IntegerField(default=0)),
                ("profile_visits", models.IntegerField(default=0)),
            ],
        ),
    ]
