# Generated by Django 4.1.5 on 2023-02-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweetreply",
            old_name="text",
            new_name="content",
        ),
    ]
