# Generated by Django 4.1.7 on 2023-03-09 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetviews",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweetreply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="home.tweetimage"
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="reply",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="home.tweetreply"
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="retweet",
            field=models.ManyToManyField(
                blank=True, related_name="retweet", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views", to="home.tweetviews"
            ),
        ),
    ]
