# Generated by Django 4.1.5 on 2023-02-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_rename_text_tweetreply_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="reply_count",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="like",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="retweet",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="views",
        ),
        migrations.CreateModel(
            name="TweetViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impression", models.IntegerField(default=0)),
                ("engagements", models.IntegerField(default=0)),
                ("detail_expands", models.IntegerField(default=0)),
                ("new_follower", models.IntegerField(default=0)),
                ("profile_visits", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tweet",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="retweet",
            field=models.ManyToManyField(
                blank=True, related_name="retweet", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views", to="home.tweetviews"
            ),
        ),
    ]
