# Generated by Django 4.1.7 on 2023-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner",
            field=models.ImageField(
                default="banners/banner.jpg", null=True, upload_to="banner/"
            ),
        ),
    ]
