# Generated by Django 4.1.7 on 2023-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="banner",
            field=models.ImageField(
                default="banner/banner.jpg", null=True, upload_to="banner/"
            ),
        ),
    ]
