# Generated by Django 4.1.5 on 2023-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_location_user_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
