# Generated by Django 4.1.5 on 2023-02-25 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(
                blank=True, validators=[django.core.validators.URLValidator()]
            ),
        ),
    ]
